name: Test simple cache.sh

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x cache.sh
      - run: ./cache.sh
      - run: ls Backup
      - run: ls Backup_*.tar.gz
      - run: cat log.txt
